# Generated by Django 2.0.3 on 2018-04-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Bad', 'Bad'), ('Good', 'Good'), ('Excelllent', 'Excellent')], max_length=2)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=264)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
