# Generated by Django 2.0.3 on 2018-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
