# Generated by Django 2.0.3 on 2018-04-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180421_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='interest1',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='interest2',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='interest3',
        ),
    ]
