# Generated by Django 2.0.3 on 2018-04-23 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='request',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
