# Generated by Django 2.0.3 on 2018-04-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
