# Generated by Django 2.0.3 on 2018-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180424_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Appliances', 'Appliances'), ('Games', 'Games'), ('Baby & Baby Care', 'Baby & Baby Care'), ('Books', 'Books'), ('CDs & Vinyl', 'CDs & Vinyl'), ('Cell Phones & Accessories', 'Cell Phones & Accessories'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Computers', 'Computers'), ('Electronics', 'Electronics'), ('Garden & Outdoor', 'Garden & Outdoor'), ('Handmade', 'Handmade'), ('Health', 'Health'), ('Household', 'Household'), ('Home & Kitchen', 'Home & Kitchen'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Luggage & Travel Gear', 'Luggage & Travel Gear'), ('Musical Instruments', 'Musical Instruments'), ('Office Products', 'Office Products'), ('Pet Supplies', 'Pet Supplies'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Toys & Games', 'Toys & Games'), ('Vehicles', 'Vehicles'), ('Video Games', 'Video Games')], max_length=30),
        ),
    ]
