# Generated by Django 2.0.3 on 2018-04-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180420_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
