# Generated by Django 2.0.3 on 2018-04-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='zipCode',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
