# Generated by Django 2.0.3 on 2018-04-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
