# Generated by Django 2.0.3 on 2018-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180421_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('Bad', 'Bad'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=12),
        ),
    ]
