# Generated by Django 2.0.3 on 2018-04-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20180422_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zipCode',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
